<?php 
// $Id$

/**
 * @file
 * Drupal hooks
 *
 * @author Stijn De Meyere
 */


/**
 * Implementation of hook_menu().
 */
function ife_menu() {
  $items = array();

  $items['admin/settings/ife'] = array(
    'title' => t('Inline Form Errors'),
    'description' => 'Administer which forms to use with field messages.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ife_settings_form'),
    'access arguments' => array('administer inline form errors'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ife.settings.inc',
  );
  $items['admin/settings/ife/%form_id/delete'] = array(
    'title' => t('Delete form_id'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ife_form_id_delete_form', 3),
    'access arguments' => array('administer inline form errors'),
    'type' => MENU_CALLBACK,
    'file' => 'ife.settings.inc',
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function ife_perm() {
  return array('administer inline form errors');
}

/**
 * Implementation of hook_help().
 */
function ife_help($path, $arg) {
  switch ($path) {
    case 'admin/help#ife':
      $output = '<p>'. t('IFE or Inline Form Errors allows you to place form submission error inline with the form elements. Three options are provided for setting your inline error behaviour. You can configure the default behaviour or override the behaviour on a per form basis. You can add as many forms as you like.') .'</p>';
      
      $output .= '<p>'. t('IFE provides three behaviours for the configured forms') .'</p>';
      
      $output .= '<ul>';
      $output .= '<li>'. t('<strong>Leave the messages in place</strong>, this option will copy the error messages and place them inline. The original error messages set by Drupal will remain in place') .'</li>';
      $output .= '<li>'. t("<strong>Show an alternate message</strong>, this option will replace the original messages with a generic error message such as 'Please correct all errors.'. This message can be set in the IFE configuration page. The original error messages are placed inline with the form elements") .'</li>';
      $output .= '<li>'. t('<strong>Remove all messages</strong>, this option will remove all error messages and place them inline with the form element') .'</li>';
      $output .= '</ul>';
      
      $output .= '<p>'. t('In all cases only the messages related to the form will be touched. All other messages will remain in tact.') .'</p>';
      
      return $output;

    case 'admin/settings/ife':
      return '<p>' . t('This page provides the interface for adding new forms to use inline errors. Just add the form_id of the forms you wish to alter. The default settings can be overridden on a per form basis.') . '</p>';
  }
}

/**
 * Menu loader function to fetch a form id
 */
function form_id_load($form_id) {
  $form_ids = ife_load_form_ids();
  if (array_key_exists($form_id, $form_ids)) {
    return $form_ids[$form_id];
  }
  else {
    return FALSE;
  }
}

/**
 * Implementation of hook_theme().
 */
function ife_theme() {
  return array(
    'ife_settings_form_ids' => array(
      'arguments' => array('form' => NULL),
      'file' => 'ife.theme.inc'
    ),
    'ife_form_element' => array(
      'arguments' => array('element' => NULL),
      'file' => 'ife.theme.inc',
      'template' => 'ife-form-element'
    ),
  );
}

/**
 *  Load all form ids from the data base
 */
function ife_load_form_ids() {
  $result = db_query("SELECT form_id, field_types, status, display FROM {ife} ORDER BY form_id");
  $form_ids = array();

  while ($form_id = db_fetch_object($result)) {
    $form_ids[$form_id->form_id] = $form_id;
  }

  return $form_ids;
}

/**
 * Helper function to determine the display settings of a form
 */
function ife_form_id_display($form_id) {
  if ($form_id->display == -1) {
    $display = variable_get('ife_display', 1);
  }
  else {
    $display = $form_id->display;
  }

  return $display;
}

/**
 * Implementation of hook_form_alter().
 */
function ife_form_alter(&$form, $form_state, $form_id) {
  $ife_options = form_id_load($form_id);
  if ($ife_options->status) {
    $display = ife_form_id_display($ife_options);
    ife_filter_form($form, $display);

    //if a general message is set run the validator
    if ($display == 1) {
      $form['#validate'][] = 'ife_form_validator';
    }
  }
}

/**
 * Function to set the general error mesage if set
 */
function ife_form_validator($form, &$form_state) {
  $form_errors = form_get_errors();
  if (!empty($form_errors)) {
    $message = check_plain(t(variable_get('ife_general_message', 'Please correct all highlighted errors and try again.')));
    drupal_set_message($message, 'error');
  }
}

/**
 * Function to recursivly go through a form and alter all valid field type elements
 */
function ife_filter_form(&$form, $display) {
  //get all possible children
  $keys = element_children($form);
  $field_types = ife_field_types();

  foreach ($keys as $key) {
    $element_type = $form[$key]['#type'];
    if (in_array($element_type, $field_types)) {
      ife_alter_form_element($form[$key], $display);
    }
    elseif ($element_type == 'fieldset' || !$element_type) {
      ife_filter_form($form[$key], $display);
    }
  }
}

/**
 * Function to add our custom theme to the element
 */
function ife_alter_form_element(&$element, $display) {
  $element['#theme'] = 'ife_form_element';
  //resend the element type, drupal sets the #type marker to markup
  $element['#field_type'] = $element['#type'];
  //add display type to element to avoid extra queries
  $element['#display_type'] = $display;
}

/**
 * Helper function that identifies the different field types default in drupal
 */
function ife_field_types() {
  return array('checkbox', 'checkboxes', 'date', 'file', 'password', 'password_confirm', 'radio', 'radios', 'select', 'textarea', 'textfield', 'weight');
}